# Generated by Django 5.2.7 on 2025-11-26 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transport",
            name="details",
            field=models.JSONField(blank=True, default="", max_length=512),
        ),
    ]
