# Generated by Django 5.2.7 on 2025-11-26 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_transport_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="transport",
            name="phone",
            field=models.CharField(default=932321, max_length=20),
            preserve_default=False,
        ),
    ]
