# Generated by Django 5.2.10 on 2026-01-29 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_transport_phone"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transport",
            old_name="phone",
            new_name="phone_number",
        ),
        migrations.RemoveField(
            model_name="transport",
            name="delivered_at",
        ),
        migrations.AlterField(
            model_name="transport",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
