# Generated by Django 5.2.10 on 2026-01-29 17:48

import api.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_rename_phone_transport_phone_number_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", api.models.CustomUserManager()),
            ],
        ),
    ]
