# Generated by Django 5.2.10 on 2026-01-29 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_user_managers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transport",
            name="details",
        ),
    ]
