# Generated by Django 5.2.10 on 2026-01-29 17:59

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_remove_transport_details"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transport",
            old_name="leaving_address",
            new_name="pickup",
        ),
        migrations.AddField(
            model_name="transport",
            name="details",
            field=models.CharField(blank=True, default="", max_length=512),
        ),
        migrations.AlterField(
            model_name="transport",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                db_index=True, max_length=128, region=None, unique=True
            ),
        ),
    ]
