# Generated by Django 5.2.10 on 2026-01-29 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_rename_leaving_address_transport_pickup_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transport",
            name="delivered_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
