# Generated by Django 5.2.10 on 2026-01-29 19:46

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_transport_delivered_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transport",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                db_index=True, max_length=128, region=None
            ),
        ),
    ]
