# Generated by Django 5.2.10 on 2026-01-29 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_alter_transport_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="transport",
            name="distance",
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
    ]
